# Generated by Django 4.2.5 on 2023-10-23 15:59

import base.models_fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Município')),
                ('geoIBGEId', models.CharField(blank=True, max_length=7, null=True, verbose_name='IBGE')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municípios',
                'ordering': ['uf', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cpf', base.models_fields.CPFField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('phone', base.models_fields.PhoneField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=15, null=True, verbose_name='Genero')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], max_length=20, null=True, verbose_name='UF')),
                ('cep', base.models_fields.CEPField(blank=True, max_length=8, verbose_name='CEP')),
                ('is_active', models.BooleanField(choices=[('F', False), ('T', True)], db_index=True, default=True, verbose_name='Ativo?')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.city', verbose_name='Município')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cnpj', base.models_fields.CNPJField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('business_name', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('PA', 'Pará'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('EX', 'Exterior')], max_length=20, null=True, verbose_name='UF')),
                ('cep', base.models_fields.CEPField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('phone', base.models_fields.PhoneField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('fax', models.CharField(blank=True, max_length=100, verbose_name='Fax')),
                ('site', models.URLField(blank=True, max_length=100, verbose_name='Site')),
                ('is_active', models.BooleanField(choices=[('F', False), ('T', True)], db_index=True, default=True, verbose_name='Ativo?')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.city', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
